//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class DETAILREPORTREVENUE : BaseViewModel
    {
        public long ID_ReportRevenue { get; set; }
        public long Day { get; set; }
        public decimal Revenue { get; set; }
        public Nullable<long> AmountBill { get; set; }
    
        public virtual REPORTREVENUE REPORTREVENUE { get; set; }
    }
}
