//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class REPORTSALE : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPORTSALE()
        {
            this.DETAILREPORTSALES = new  ObservableCollection<DETAILREPORTSALE>();
        }
    
        public long ID { get; set; }
        public long Month { get; set; }
        public long Year { get; set; }
        public long TotalAmout { get; set; }
        public long TotalRevenue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DETAILREPORTSALE> DETAILREPORTSALES { get; set; }
    }
}
