name: Dotnet-Stryker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Test:
    strategy:
      matrix:
        configuration: [windows-latest]

    runs-on: windows-latest

    env:
      Solution_Name: MainProject/MainProject.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore Packages
        run: nuget restore MainProject/MainProject.sln

      - name: Execute unit tests
        run: dotnet test MainProject/MainProject.csproj

      - name: Create new tool manifest
        run: dotnet new tool-manifest

      - name: Install dotnet stryker
        run: dotnet tool install dotnet-stryker

      - name: Init dotnet stryker
        run: dotnet new console

      - name: Execute mutation tests
        run: dotnet stryker --config-file  MainProject/stryker-config.json
